version: "3.8"

services:
  #  MongoDB for storing sensor data
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - manufacturing_network

  #  Zookeeper (Required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - manufacturing_network

  #  Kafka Broker (Message Queue)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - manufacturing_network

  #  Apache Spark Master
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - manufacturing_network

  #  Apache Spark Worker
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    networks:
      - manufacturing_network

  #  Sensor Data Generator (Sends data to Kafka)
  sensor-data-generator:
    build: ./sensor_simulator
    container_name: sensor-generator
    depends_on:
      - kafka
    networks:
      - manufacturing_network

  #  Spark Streaming Consumer (Kafka → MongoDB)
  spark-streaming:
    build: ./spark_streaming
    container_name: spark-streaming
    depends_on:
      - kafka
      - mongodb
    environment:
      - PYSPARK_SUBMIT_ARGS=--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 pyspark-shell
    networks:
      - manufacturing_network

networks:
  manufacturing_network:
    driver: bridge